[package]
name = "society"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
cfg-if = "1.0.0"
cstr = "0.2.11"
image = "0.24.5"
rayon = "1.6.1"
thiserror = "1.0.38"